-- MySQL Script generated by MySQL Workbench
-- Thu Jul 11 19:27:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema museudosgames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema museudosgames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `museudosgames` DEFAULT CHARACTER SET utf8 ;
USE `museudosgames` ;

-- -----------------------------------------------------
-- Table `museudosgames`.`Jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Jogo` (
  `idJogo` INT NOT NULL,
  `nome_jogo` VARCHAR(45) NULL,
  `imagem_capa` VARCHAR(1000) NULL,
  `descricao` VARCHAR(200) NULL,
  `data_lancamento` DATETIME NULL,
  `numero_jogadores` INT NULL,
  `classificacao_etaria` VARCHAR(1) NULL,
  PRIMARY KEY (`idJogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Genero` (
  `idGenero` INT NOT NULL,
  `nome_genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`JogoGenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`JogoGenero` (
  `idJogo` INT NOT NULL,
  `idGenero` INT NOT NULL,
  PRIMARY KEY (`idJogo`, `idGenero`),
  INDEX `fk_GeneroJogo_Genero1_idx` (`idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_GeneroJogo_Jogo1`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GeneroJogo_Genero1`
    FOREIGN KEY (`idGenero`)
    REFERENCES `museudosgames`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`ImagemGameplay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`ImagemGameplay` (
  `idImagemGameplay` INT NOT NULL,
  `idJogo` INT NOT NULL,
  `URL_imagem_gameplay` VARCHAR(1000) NULL,
  `ImagemGameplaycol` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagemGameplay`),
  INDEX `idJogo_idx` (`idJogo` ASC) VISIBLE,
  CONSTRAINT `idJogo`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`Publicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Publicador` (
  `idPublicador` INT NOT NULL,
  `nome_publicador` VARCHAR(45) NULL,
  PRIMARY KEY (`idPublicador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`Plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Plataforma` (
  `idPlataforma` INT NOT NULL,
  `nome_plataforma` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlataforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`JogoPlataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`JogoPlataforma` (
  `idJogo` INT NOT NULL,
  `idPlataforma` INT NOT NULL,
  PRIMARY KEY (`idJogo`, `idPlataforma`),
  INDEX `fk_JogoPlataforma_Plataforma1_idx` (`idPlataforma` ASC) VISIBLE,
  CONSTRAINT `fk_JogoPlataforma_Jogo1`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JogoPlataforma_Plataforma1`
    FOREIGN KEY (`idPlataforma`)
    REFERENCES `museudosgames`.`Plataforma` (`idPlataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`Franquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Franquia` (
  `idFranquia` INT NOT NULL,
  `nome_franquia` VARCHAR(45) NULL,
  PRIMARY KEY (`idFranquia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`JogoPublicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`JogoPublicador` (
  `idJogo` INT NOT NULL,
  `idPublicador` INT NOT NULL,
  PRIMARY KEY (`idJogo`, `idPublicador`),
  INDEX `fk_Jogo_has_Publicador_Publicador1_idx` (`idPublicador` ASC) VISIBLE,
  INDEX `fk_Jogo_has_Publicador_Jogo1_idx` (`idJogo` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_has_Publicador_Jogo1`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_Publicador_Publicador1`
    FOREIGN KEY (`idPublicador`)
    REFERENCES `museudosgames`.`Publicador` (`idPublicador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`Desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`Desenvolvedor` (
  `idDesenvolvedor` INT NOT NULL,
  `nome_desenvolvedor` VARCHAR(45) NULL,
  PRIMARY KEY (`idDesenvolvedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`JogoDesenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`JogoDesenvolvedor` (
  `idDesenvolvedor` INT NOT NULL,
  `idJogo` INT NOT NULL,
  PRIMARY KEY (`idDesenvolvedor`, `idJogo`),
  INDEX `fk_Desenvolvedor_has_Jogo_Jogo1_idx` (`idJogo` ASC) VISIBLE,
  INDEX `fk_Desenvolvedor_has_Jogo_Desenvolvedor1_idx` (`idDesenvolvedor` ASC) VISIBLE,
  CONSTRAINT `fk_Desenvolvedor_has_Jogo_Desenvolvedor1`
    FOREIGN KEY (`idDesenvolvedor`)
    REFERENCES `museudosgames`.`Desenvolvedor` (`idDesenvolvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desenvolvedor_has_Jogo_Jogo1`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museudosgames`.`JogoFranquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museudosgames`.`JogoFranquia` (
  `idJogo` INT NOT NULL,
  `idFranquia` INT NOT NULL,
  PRIMARY KEY (`idJogo`, `idFranquia`),
  INDEX `fk_Jogo_has_Franquia_Franquia1_idx` (`idFranquia` ASC) VISIBLE,
  INDEX `fk_Jogo_has_Franquia_Jogo1_idx` (`idJogo` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_has_Franquia_Jogo1`
    FOREIGN KEY (`idJogo`)
    REFERENCES `museudosgames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_Franquia_Franquia1`
    FOREIGN KEY (`idFranquia`)
    REFERENCES `museudosgames`.`Franquia` (`idFranquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
